

server:
  port: 18083

spring:
  application:
    name: spcld-ribbon-client

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:18080/eureka/
