
server:
  port: 18080
srping:
  application:
    name: spcld-eureka-server
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://localhost:18080/eureka/
