
server:
  port: 18081

spring:
  application:
    name: spcld-eureka-client1

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:18080/eureka/
